name: pull_to_refresh
description: A patched to support felxible Pull-to-Refresh functionality.
version: 1.6.5
homepage: https://github.com/triztian/flutter_pulltorefresh

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
